config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root                      :to => "app#home"
  get       '/home',        :to => "app#home"
  get       '/about',       :to => "app#about"
  get       '/contact',     :to => "app#contact"
  get       '/profile',     :to => "users#show"
  get       '/signup',      :to => "users#new"
  get       '/login',       :to => "sessions#new"
  post      '/login',       :to => "sessions#create"
  delete    '/logout',       :to => "sessions#destroy"
  resources                 :users
  resources                 :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png], message: "must be a valid image format" }, size: { less_than: 5.megabytes, message: "should be less than 5MB" }

  def display_image
    image.variant(resize_to_limit: [500, 500])
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :posts, dependent: :destroy
  before_save { self.email = email.downcase }
  EMAIL_PATTERN = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates(:name,
            presence: true,
            length: { maximum: 50 },
           )
  validates(:email,
            presence: true,
            length: { maximum: 255 },
            format: { with: EMAIL_PATTERN },
            uniqueness: true,
           )
  validates(:password,
            presence: true,
            length: { minimum: 6 },
	    allow_nil: true,
           )
  has_secure_password

  class << self
	# returns the hash digest of the given string
	def digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# remember token
	def new_token
		SecureRandom.urlsafe_base64
	end
  end

  # remembers a user of session persistence
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # removes user from session persistence
  def forget
	update_attribute(:remember_digest, nil)
  end

  def feed
    Post.all()
    #Post.where("user_id = ?", id)
  end

  # checks auth state, returns boolean
  def authenticated?(remember_token)
	if remember_digest.nil?
		false
	else
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def home
    if logged_in?
      @post = current_user.posts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    else
      @feed_items = Post.all().paginate(page: params[:page])
    end
  end

  def profile
  end

  def about
  end

  def contact
  end

  def construction
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in to continue"
      redirect_to login_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    if @post.save
      flash[:success] = "Post Created!"
      redirect_to root_url
    else
      render 'app/home'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post Deleted"
    redirect_to request.referrer || root_url
  end

  def post_params
    params.require(:post).permit(:content, :image)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      # log in
      log_in user
      if params[:session][:remember_me] == '1'
	remember(user)
      else
	forget(user)
      end
      redirect_to user_url(user)
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Welcome to ThankTank!"
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destory
    flash[:success] = "User deleted"
    redirected_to users_url
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in"
      redirect_to login_url
    end
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/app_helper.rb
module AppHelper
  # returns the full title, with or without title input
  def full_title(page_title = '')
    base_title = "ThankTank"
    if page_title.empty?
      base_title
    else
      base_title + " | " + page_title
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # logs in the user
  def log_in(user)
    session[:user_id] = user.id
  end

  # remembers the user
  def remember(user)
	user.remember
	cookies.permanent.encrypted[:user_id] = user.id
	cookies.permanent[:remember_token] = user.remember_token
  end

  # forgets a user
  def forget(user)
	user.forget
	cookies.delete(:user_id)
	cookies.delete(:remember_token)
  end

  # returns the currently logged in user (if any)
  def current_user
	if (user_id = session[:user_id])
	  @current_user ||= User.find_by(id: user_id)
	elsif (user_id = cookies.encrypted[:user_id])
	  user = User.find_by(id: user_id)
	  if user && user.authenticated?(cookies[:remember_token])
		log_in user
        @current_user = user
	  end
	end
  end

  def current_user?(user)
    user && user == current_user
  end

  # returns bool if a user is logged in
  def logged_in?
    !current_user.nil?
  end

  # logs out current user
  def log_out
	forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # returns gravatar for the given user
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/app/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<br>
<br>
<p class="about">ThankTank is a social platform for gratitude. You may share your most meaninful thoughts and moments in a space intended for positivity, mindfulness, and compassion.</p>
<br>
<p class="about">ThankTank is dedicated to serving water to those without access. Every post, comment, and like on this platform is a drop of water donated to someone in need.</p>
<br>
<p class="about">While one drop of water is close to nothing, it took many drops of water to fill our oceans.</p>
<p class="about">And like these drops of water, a single post of gratitude may appear to be close to nothing, but these digital drops of gratitude are are what fill the ThankTank.</p>
<p class="about">It will take many drops to provide for those without, so come by and make your donation today!</p>
<br>
<br>
<br>
<p class="quote">“We ourselves feel that what we are doing is just a drop in the ocean. But the ocean would be less because of that missing drop.”</p>
<p class="quote">-Mother Teresa</p>

app/views/app/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<br>
<br>
<p class="meta">connect on <a href="https://www.linkedin.com/in/benjamin-k-740412149/">LinkedIn</a> or send an <a href="mailto:1996byk@gmail.com?subject=ThankTank%20Contact">email</a></p>
<p class="meta">find more at my personal site, <a href="https://www.benkim.dev">benkim.dev</a></p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/app/home.html.erb
<% if logged_in? %>
	<div class="row">
		<aside class="col-md-4">
			<section class="user_info">
				<%= render 'shared/user_info' %>
			</section>
			<section class="post_info">
				<%= render 'shared/post_form' %>
			</section>
		</aside>
		<div class="col-md-8">
			<h3>Global Gratitude Feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
<% else %>
<div>
	<div class="center jumbotron">
		<h1>Welcome to ThankTank</h1>
		<h2>Express what makes you grateful. Share what makes you smile! Every post is a drop of water donated to someone without access.</h2>
		<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	</div>
	<div>
		<h3>Global Gratitude Feed</h3>
		<%= render 'shared/feed' %>
	</div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div id="site-meta">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </div>
  <div id="author-meta">
    <ul>
      <li>
        <a href="https://www.thanktank.app">ThankTank</a> by Benjamin Kim
      </li>
      <li>
        <a href="https://linkedin.com/in/ben-kim-740412149/"><i class="fa fa-linkedin social"></i></a>
        <a href="https://github.com/benjaminykim"><i class="fa fa-github social"></i></a>
        <a href="https://www.benkim.dev"><i class="fa fa-laptop social"></i></a>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-178514031-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-178514031-2');
</script>

  <div class="container">
    <%= link_to image_tag("water.png", alt: "ThankTank Logo", height: 40, width: 40), root_path, id: "logo-icon" %>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if logged_in? %>
          <li><%= link_to "Home", home_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log Out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;1,100;1,300&display=swap" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"> </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag asset_path('water.png') %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
	<%= link_to gravatar_for(post.user, size: 50), post.user %>
	<span class="user"><%= link_to post.user.name, post.user %></span>
	<span class="content">
		<%= post.content %>
		<%= image_tag post.display_image if post.image.attached? %>
	</span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(post.created_at) %> ago.
		<% if current_user?(post.user) %>
			<%= link_to "delete", post, method: :delete,
						data: { confirm: "Are you sure?" } %>
		<% end %>
	</span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="posts">
		<%= render @feed_items %>
	</ol>
	<%= will_paginate @feed_items,
		params: { controller: :app, action: :home } %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Drop some gratitude..." %>
	</div>
	<%= f.submit "Post", class: "btn btn-primary" %>
	<span class="image">
		<%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
	</span>
<% end %>

<script type="text/javascript">
	$("#post_image").bind("change", function() {
		const size_in_megabytes = this.files[0].size/1024/1024;
		if (size_in_megabytes > 5) {
			alert("Maximum image size is 5 MB. Please choose a smaller file");
			$("post_image").val("");
		}
	});
</script>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>
<h1>Update your profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_with(model: @user, local: true) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control" %>

			<%= f.label :email %>
			<%= f.email_field :email, class: "form-control" %>

			<%= f.label :password %>
			<%= f.password_field :password, class: "form-control" %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: "form-control" %>

			<%= f.submit "Save changes", class: "btn btn-primary" %>
		<% end %>
		<div class="gravatar_edit">
			<%= gravatar_for @user %>
			<a href="https://gravatar.com/emails" target="_blank">Change</a>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All Users")  %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h1>Sign Up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_with(model: @user, local: true) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control" %>

			<%= f.label :email %>
			<%= f.email_field :email, class: "form-control" %>

			<%= f.label :password %>
			<%= f.password_field :password, class: "form-control" %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: "form-control" %>

			<%= f.submit "Create account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user-info">
			<h1>
				<%= gravatar_for(@user) %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
	<div class="col-md-8">
		<% if @user.posts.any? %>
			<h3><%= @user.name %>'s Gratitude Stream</h3>
			<ol class="posts">
				<%= render @posts %>
			</ol>
			<%= will_paginate @posts %>
		<% end %>
	</div>
</div>